name: Lint

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: Install shellcheck and dependencies
        run: |
          # node:12.6-buster-slim doesn't have sudo, but root by default.
          SUDO_AVAILABLE=$(if command -v sudo 2> /dev/null; then echo 1; fi)
          ${SUDO_AVAILABLE:+sudo} apt-get update
          ${SUDO_AVAILABLE:+sudo} apt-get install -y make wget tar xz-utils
          scversion="stable"
          wget -qO- "https://github.com/koalaman/shellcheck/releases/download/${scversion?}/shellcheck-${scversion?}.linux.x86_64.tar.xz" | tar -xJv
          ${SUDO_AVAILABLE:+sudo} \
            cp "shellcheck-${scversion}/shellcheck" /usr/bin/
      - name: Shellcheck version
        run: shellcheck --version
      - name: Lint
        run: /bin/sh -c 'make lint'
