name: Test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: Environment
        run: |
          echo ::set-env name=SUDO_AVAIL::$(if command -v sudo \
            2> /dev/null; then echo 1; fi)
      - name: Update repositories
        run: |
          ${SUDO_AVAIL:+sudo} apt-get update
      - name: Install dependencies
        run: |
          ${SUDO_AVAIL:+sudo} apt-get install -y make stow sudo wget curl
      - name: Cache kcov
        id: cache-kcov
        uses: actions/cache@v1
        with:
          path: kcov-master
          key: ${{ runner.os }}-kcov-master
      - name: Install kcov install dependencies
        run: |
          ls -al
