name: Test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: Install stow and dependencies
        run: |
          # node:12.6-buster-slim doesn't have sudo, but root by default.
          SUDO_AVAILABLE=$(if command -v sudo 2> /dev/null; then echo 1; fi)
          ${SUDO_AVAILABLE:+sudo} apt-get update
          ${SUDO_AVAILABLE:+sudo} apt-get install -y make stow sudo wget curl \
            python3 tar xz-utils cmake build-essential zlib1g-dev libssl-dev \
            binutils-dev libcurl4-openssl-dev libdw-dev libiberty-dev
      - name: Install kcov
        run: |
          wget https://github.com/SimonKagstrom/kcov/archive/master.tar.gz
          tar xzf master.tar.gz
          cd kcov-master
          mkdir -p build
          cd build
          cmake ..
          make
          sudo make install
          cd ../..
          rm -rf kcov-master
      - name: Test
        run: make test
      - name: Upload coverage result
        run: bash <(curl -s https://codecov.io/bash)
