name: Test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: Cache Kcov
        id: cache-kcov
        uses: actions/cache@v1
        with:
          path: kcov-master
          key: ${{ runner.os }}-kcov-master
      - name: Check if sudo is available
        run: |
          echo ::set-env name=SUDO_AVAIL::$(if command -v sudo \
            2> /dev/null; then echo 1; fi)
      - name: Update repositories
        run: |
          ${SUDO_AVAIL:+sudo} apt-get update
      - name: Install stow and dependencies
        run: |
          ${SUDO_AVAIL:+sudo} apt-get install -y make stow sudo wget curl \
            libcurl4-openssl-dev binutils-dev
      - name: Install kcov dependencies
        if: steps.cache-kcov.outputs.cache-hit != 'true'
        run: |
          ${SUDO_AVAIL:+sudo} apt-get install -y python3 tar xz-utils \
            cmake zlib1g-dev libssl-dev \
            libdw-dev libiberty-dev build-essential
      - name: Build Kcov
        if: steps.cache-kcov.outputs.cache-hit != 'true'
        run: |
          wget https://github.com/SimonKagstrom/kcov/archive/master.tar.gz
          tar xzf master.tar.gz
          cd kcov-master
          mkdir -p build
          cd build
          cmake ..
          make
          cd ../..
      - name: Install Kcov
        run: |
          cd kcov-master/build
          sudo make install
          cd ../..
      - name: Test
        run: make test
      - name: Upload coverage result to codecov
        run: bash <(curl -s https://codecov.io/bash)
      - name: Upload coverage result to codacy
        run: |
          export CODACY_PROJECT_TOKEN=${{ secrets.CODACY_PROJECT_TOKEN }}
          bash <(curl -Ls https://coverage.codacy.com/get.sh)
